version: "3"

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  rosetta:
    image: zetanode:latest
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - zetacore
    entrypoint: ["zetacored", "rosetta", "--tendermint", "localnet-zetacore-1:26657", "--grpc", "localnet-zetacore-1:9090", "--network", "athens_101-1", "--blockchain",  "zetacore"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - zetacore
      - zetaclient
      - eth
      - bitcoin
    ports:
      - "1317:1317"
      - "9545:9545"
      - "9546:9546"

  zetacore:
    image: zetanode:latest
    build:
      context: ../../.
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      #scale up immediately via script if desired replicas is >2
      replicas: 2
    networks:
      - mynetwork
    entrypoint: ["/root/genesis.sh", "2"] #set the argument for geneis.sh to replcas

  zetaclient:
    image: zetanode:latest
    build:
      context: ../../.
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      #scale up immediately via script if desired replicas is >2
      replicas: 2
    networks:
      - mynetwork
    entrypoint: /root/start-zetaclientd-genesis.sh
    environment:
      - ETHDEV_ENDPOINT=http://eth:8545

  eth:
    image: ethereum/client-go:v1.10.26
    expose:
      - 8545
    networks:
      - mynetwork
    # TODO: Fix runing GETH open to the world on 8545 with nginx by discovering own IP and setting it for http.addr
    entrypoint: ["geth", "--dev", "--http", "--http.addr", "0.0.0.0", "--http.vhosts", "*", "--http.api", "eth,web3,net", "--http.corsdomain", "https://remix.ethereum.org", "--dev.period", "2"]

  bitcoin:
    image: ruimarinho/bitcoin-core:22 # version 23 is not working with btcd 0.22.0 due to change in createwallet rpc
    networks:
      - mynetwork
    expose:
      - 18443
    command:
      -printtoconsole
      -regtest=1
      -rpcallowip=172.20.0.0/16
      -rpcbind=0.0.0.0
      -rpcauth=smoketest:63acf9b8dccecce914d85ff8c044b78b$$5892f9bbc84f4364e79f0970039f88bdd823f168d4acc76099ab97b14a766a99
      -txindex=1

  orchestrator:
    image: orchestrator:latest
    container_name: orchestrator
    build:
      context: ../../.
      dockerfile: contrib/localnet/orchestrator/Dockerfile
    depends_on:
      - zetacore
      - eth
      - bitcoin
    hostname: orchestrator
    networks:
      - mynetwork
    entrypoint: ["/work/start.sh", "local"]

